In [1]:
from pandas import *

df=read_csv('Kitap1.csv')
df2=read_csv('users1.csv')
df.head()

   UserID  MovieID  Rating  Timestamp
0       1     1193       5  978300760
1       1      661       3  978302109
2       1      914       3  978301968
3       1     3408       4  978300275
4       1     2355       5  978824291

In [2]:
df2.head()

   UserID Gender  Age  Occupation  ZipCode
0       1      F    1          10    48067
1       2      M   56          16    70072
2       3      M   25          15    55117
3       4      M   45           7     2460
4       5      M   25          20    55455

In [3]:
result=df.merge(df2, on='UserID',how='inner')
result.head()

   UserID  MovieID  Rating  Timestamp Gender  Age  Occupation  ZipCode
0       1     1193       5  978300760      F    1          10    48067
1       1      661       3  978302109      F    1          10    48067
2       1      914       3  978301968      F    1          10    48067
3       1     3408       4  978300275      F    1          10    48067
4       1     2355       5  978824291      F    1          10    48067

In [4]:
df1=read_csv('movieoutput.csv',encoding='latin-1')

In [5]:
df1.head()

   MovieID                               Title                        Genres;
0        1                    Toy Story (1995)   Animation|Children's|Comedy;
1        2                      Jumanji (1995)  Adventure|Children's|Fantasy;
2        3             Grumpier Old Men (1995)                Comedy|Romance;
3        4            Waiting to Exhale (1995)                  Comedy|Drama;
4        5  Father of the Bride Part II (1995)                        Comedy;

In [6]:
result1 = result.merge( df1, on = 'MovieID')

def change_gender(x):
    if x=='F':
        return 1
    return 0
result1['Gender'] = result1['Gender'].apply(change_gender)

result1.head()

,UserID,MovieID,Rating,Timestamp,Gender,Age,Occupation,ZipCode,Title,Genres;
0,1,1193,5,978300760,1,1,10,48067,One Flew Over the Cuckoo's Nest (1975),Drama;
1,1,661,3,978302109,1,1,10,48067,James and the Giant Peach (1996),Animation|Children's|Musical;
2,1,914,3,978301968,1,1,10,48067,My Fair Lady (1964),Musical|Romance;
3,1,3408,4,978300275,1,1,10,48067,Erin Brockovich (2000),Drama;
4,1,2355,5,978824291,1,1,10,48067,Bug's Life A (1998),Animation|Children's|Comedy;

In [7]:
def Action(x):
    if "Action" in x:
        return 1
    else:
        return 0
def Adventure(x):
    if "Adventure" in x:
        return 1
    else:
        return 0
def Animation(x):
    if "Animation" in x:
        return 1
    else:
        return 0
def Children(x):
    if "Children's" in x:
        return 1
    else:
        return 0

def Comedy(x):
    if "Comedy" in x:
        return 1
    else:
        return 0
    
def Crime(x):
    if "Crime" in x:
        return 1
    else:
        return 0    
    
def Documentary(x):
    if "Documentary" in x:
        return 1
    else:
        return 0   
    
def Drama(x):
    if "Drama" in x:
        return 1
    else:
        return 0
def Fantasy(x):
    if "Fantasy" in x:
        return 1
    else:
        return 0
def FilmNoir(x):
    if "Film-Noir" in x:
        return 1
    else:
        return 0    
def Horror(x):
    if "Horror" in x:
        return 1
    else:
        return 0    
def Musical(x):
    if "Musical" in x:
        return 1
    else:
        return 0    
def Mystery(x):
    if "Mystery" in x:
        return 1
    else:
        return 0    
def Romance(x):
    if "Romance" in x:
        return 1
    else:
        return 0    
    
def SciFi(x):
    if "Sci-Fi" in x:
        return 1
    else:
        return 0    
def Thriller(x):
    if "Thriller" in x:
        return 1
    else:
        return 0    
def War(x):
    if "War" in x:
        return 1
    else:
        return 0    
def Western(x):
    if "Western" in x:
        return 1
    else:
        return 0     
    
    

cats=["Action", "Adventure","Animation"," Children's", "Comedy","Crime","Documentary","Drama",\
 "Fantasy","Film-Noir","Horror","Musical","Mystery","Romance","Sci-Fi","Thriller","War","Western" ]
#for cat in cats:
    #df[cat] = 0
#    df[cat] = df['Genres;'].apply(check)
result1['Action'] = result1['Genres;'].apply(Action)
result1['Adventure'] = result1['Genres;'].apply(Adventure)
result1['Animation'] = result1['Genres;'].apply(Animation)
result1["Children's"] = result1['Genres;'].apply(Children)
result1['Comedy'] = result1['Genres;'].apply(Comedy)
result1['Crime'] = result1['Genres;'].apply(Crime)
result1['Documentary'] = result1['Genres;'].apply(Documentary)
result1['Drama'] = result1['Genres;'].apply(Drama)
result1['Fantasy'] = result1['Genres;'].apply(Fantasy)
result1['Film-Noir'] = result1['Genres;'].apply(FilmNoir)
result1['Horror'] = result1['Genres;'].apply(Horror)
result1['Musical'] = result1['Genres;'].apply(Musical)
result1['Mystery'] = result1['Genres;'].apply(Mystery)
result1['Romance'] = result1['Genres;'].apply(Romance)
result1['Sci-Fi'] = result1['Genres;'].apply(SciFi)
result1['Thriller'] = result1['Genres;'].apply(Thriller)
result1['War'] = result1['Genres;'].apply(War)
result1['Western'] = result1['Genres;'].apply(Western)

In [8]:
result1.drop(['Genres;'],axis=1,inplace=True)
result1.head()

,UserID,MovieID,Rating,Timestamp,Gender,Age,Occupation,ZipCode,Title,Action,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,1193,5,978300760,1,1,10,48067,One Flew Over the Cuckoo's Nest (1975),0,...,0,0,0,0,0,0,0,0,0,0
1,1,661,3,978302109,1,1,10,48067,James and the Giant Peach (1996),0,...,0,0,0,1,0,0,0,0,0,0
2,1,914,3,978301968,1,1,10,48067,My Fair Lady (1964),0,...,0,0,0,1,0,1,0,0,0,0
3,1,3408,4,978300275,1,1,10,48067,Erin Brockovich (2000),0,...,0,0,0,0,0,0,0,0,0,0
4,1,2355,5,978824291,1,1,10,48067,Bug's Life A (1998),0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
averagerate=result1.groupby(['MovieID']).mean()

In [10]:
averagerate

,UserID,Rating,Timestamp,Gender,Age,Occupation,ZipCode,Action,Adventure,Animation,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
MovieID,,,,,,,,,,,,,,,,,,,,,
1,1,5,978824268,1,1,10,48067,0,0,1,...,0,0,0,0,0,0,0,0,0,0
48,1,5,978824351,1,1,10,48067,0,0,1,...,0,0,0,1,0,1,0,0,0,0
150,1,5,978301777,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
260,1,4,978300760,1,1,10,48067,1,1,0,...,1,0,0,0,0,0,1,0,0,0
527,1,5,978824195,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,1,0
531,1,4,978302149,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
588,1,4,978824268,1,1,10,48067,0,0,1,...,0,0,0,1,0,0,0,0,0,0
594,1,4,978302268,1,1,10,48067,0,0,1,...,0,0,0,1,0,0,0,0,0,0
595,1,5,978824268,1,1,10,48067,0,0,1,...,0,0,0,1,0,0,0,0,0,0
608,1,4,978301398,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,1,0,0
661,1,3,978302109,1,1,10,48067,0,0,1,...,0,0,0,1,0,0,0,0,0,0
720,1,3,978300760,1,1,10,48067,0,0,1,...,0,0,0,0,0,0,0,0,0,0
745,1,3,978824268,1,1,10,48067,0,0,1,...,0,0,0,0,0,0,0,1,0,0
783,1,4,978824291,1,1,10,48067,0,0,1,...,0,0,0,1,0,0,0,0,0,0
914,1,3,978301968,1,1,10,48067,0,0,0,...,0,0,0,1,0,1,0,0,0,0
919,1,4,978301368,1,1,10,48067,0,1,0,...,0,0,0,1,0,0,0,0,0,0
938,1,4,978301752,1,1,10,48067,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1022,1,5,978300055,1,1,10,48067,0,0,1,...,0,0,0,1,0,0,0,0,0,0
1028,1,5,978301777,1,1,10,48067,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1029,1,5,978302205,1,1,10,48067,0,0,1,...,0,0,0,1,0,0,0,0,0,0
1035,1,5,978301753,1,1,10,48067,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1097,1,4,978301953,1,1,10,48067,0,0,0,...,1,0,0,0,0,0,1,0,0,0
1193,1,5,978300760,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1197,1,3,978302268,1,1,10,48067,1,1,0,...,0,0,0,0,0,1,0,0,0,0
1207,1,4,978300719,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1246,1,4,978302091,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1270,1,5,978300055,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1287,1,5,978302039,1,1,10,48067,1,1,0,...,0,0,0,0,0,0,0,0,0,0
1545,1,4,978824139,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1566,1,4,978824330,1,1,10,48067,0,1,1,...,0,0,0,1,0,0,0,0,0,0
1721,1,4,978300055,1,1,10,48067,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1836,1,5,978300172,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1907,1,4,978824330,1,1,10,48067,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1961,1,5,978301590,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1962,1,4,978301753,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2018,1,4,978301777,1,1,10,48067,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2028,1,5,978301619,1,1,10,48067,1,0,0,...,0,0,0,0,0,0,0,0,1,0
2294,1,4,978824291,1,1,10,48067,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2321,1,3,978302205,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2340,1,3,978300103,1,1,10,48067,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2355,1,5,978824291,1,1,10,48067,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2398,1,4,978302281,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2687,1,3,978824268,1,1,10,48067,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2692,1,4,978301570,1,1,10,48067,1,0,0,...,0,0,0,0,0,1,0,0,0,0
2762,1,4,978302091,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2791,1,4,978302188,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2797,1,4,978302039,1,1,10,48067,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2804,1,5,978300719,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2918,1,4,978302124,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3105,1,5,978301713,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3114,1,4,978302174,1,1,10,48067,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3186,1,4,978300019,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3408,1,4,978300275,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
x=averagerate.drop(['Rating','Timestamp','UserID','ZipCode'],axis=1)
y= averagerate.Rating

In [12]:
x

,Gender,Age,Occupation,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
MovieID,,,,,,,,,,,,,,,,,,,,,
1,1,1,10,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
48,1,1,10,0,0,1,1,0,0,0,...,0,0,0,1,0,1,0,0,0,0
150,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
260,1,1,10,1,1,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
527,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
531,1,1,10,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
588,1,1,10,0,0,1,1,1,0,0,...,0,0,0,1,0,0,0,0,0,0
594,1,1,10,0,0,1,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
595,1,1,10,0,0,1,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
608,1,1,10,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
661,1,1,10,0,0,1,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
720,1,1,10,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
745,1,1,10,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
783,1,1,10,0,0,1,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
914,1,1,10,0,0,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
919,1,1,10,0,1,0,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
938,1,1,10,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1022,1,1,10,0,0,1,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1028,1,1,10,0,0,0,1,1,0,0,...,0,0,0,1,0,0,0,0,0,0
1029,1,1,10,0,0,1,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1035,1,1,10,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1097,1,1,10,0,0,0,1,0,0,0,...,1,0,0,0,0,0,1,0,0,0
1193,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1197,1,1,10,1,1,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
1207,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1246,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1270,1,1,10,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
1287,1,1,10,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1545,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1566,1,1,10,0,1,1,1,1,0,0,...,0,0,0,1,0,0,0,0,0,0
1721,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1836,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1907,1,1,10,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1961,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1962,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2018,1,1,10,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2028,1,1,10,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2294,1,1,10,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2321,1,1,10,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2340,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2355,1,1,10,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2398,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2687,1,1,10,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2692,1,1,10,1,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
2762,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2791,1,1,10,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2797,1,1,10,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
2804,1,1,10,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2918,1,1,10,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3105,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3114,1,1,10,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3186,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3408,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
def change_rating(x):
    result= x*10**6
    result=round(result)
    return result
averagerate['Rating'] = averagerate['Rating'].apply(change_rating)
averagerate.groupby(['MovieID']).mean()

,UserID,Rating,Timestamp,Gender,Age,Occupation,ZipCode,Action,Adventure,Animation,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
MovieID,,,,,,,,,,,,,,,,,,,,,
1,1,5000000,978824268,1,1,10,48067,0,0,1,...,0,0,0,0,0,0,0,0,0,0
48,1,5000000,978824351,1,1,10,48067,0,0,1,...,0,0,0,1,0,1,0,0,0,0
150,1,5000000,978301777,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
260,1,4000000,978300760,1,1,10,48067,1,1,0,...,1,0,0,0,0,0,1,0,0,0
527,1,5000000,978824195,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,1,0
531,1,4000000,978302149,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
588,1,4000000,978824268,1,1,10,48067,0,0,1,...,0,0,0,1,0,0,0,0,0,0
594,1,4000000,978302268,1,1,10,48067,0,0,1,...,0,0,0,1,0,0,0,0,0,0
595,1,5000000,978824268,1,1,10,48067,0,0,1,...,0,0,0,1,0,0,0,0,0,0
608,1,4000000,978301398,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,1,0,0
661,1,3000000,978302109,1,1,10,48067,0,0,1,...,0,0,0,1,0,0,0,0,0,0
720,1,3000000,978300760,1,1,10,48067,0,0,1,...,0,0,0,0,0,0,0,0,0,0
745,1,3000000,978824268,1,1,10,48067,0,0,1,...,0,0,0,0,0,0,0,1,0,0
783,1,4000000,978824291,1,1,10,48067,0,0,1,...,0,0,0,1,0,0,0,0,0,0
914,1,3000000,978301968,1,1,10,48067,0,0,0,...,0,0,0,1,0,1,0,0,0,0
919,1,4000000,978301368,1,1,10,48067,0,1,0,...,0,0,0,1,0,0,0,0,0,0
938,1,4000000,978301752,1,1,10,48067,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1022,1,5000000,978300055,1,1,10,48067,0,0,1,...,0,0,0,1,0,0,0,0,0,0
1028,1,5000000,978301777,1,1,10,48067,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1029,1,5000000,978302205,1,1,10,48067,0,0,1,...,0,0,0,1,0,0,0,0,0,0
1035,1,5000000,978301753,1,1,10,48067,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1097,1,4000000,978301953,1,1,10,48067,0,0,0,...,1,0,0,0,0,0,1,0,0,0
1193,1,5000000,978300760,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1197,1,3000000,978302268,1,1,10,48067,1,1,0,...,0,0,0,0,0,1,0,0,0,0
1207,1,4000000,978300719,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1246,1,4000000,978302091,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1270,1,5000000,978300055,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1287,1,5000000,978302039,1,1,10,48067,1,1,0,...,0,0,0,0,0,0,0,0,0,0
1545,1,4000000,978824139,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1566,1,4000000,978824330,1,1,10,48067,0,1,1,...,0,0,0,1,0,0,0,0,0,0
1721,1,4000000,978300055,1,1,10,48067,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1836,1,5000000,978300172,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1907,1,4000000,978824330,1,1,10,48067,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1961,1,5000000,978301590,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1962,1,4000000,978301753,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2018,1,4000000,978301777,1,1,10,48067,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2028,1,5000000,978301619,1,1,10,48067,1,0,0,...,0,0,0,0,0,0,0,0,1,0
2294,1,4000000,978824291,1,1,10,48067,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2321,1,3000000,978302205,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2340,1,3000000,978300103,1,1,10,48067,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2355,1,5000000,978824291,1,1,10,48067,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2398,1,4000000,978302281,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2687,1,3000000,978824268,1,1,10,48067,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2692,1,4000000,978301570,1,1,10,48067,1,0,0,...,0,0,0,0,0,1,0,0,0,0
2762,1,4000000,978302091,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2791,1,4000000,978302188,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2797,1,4000000,978302039,1,1,10,48067,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2804,1,5000000,978300719,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2918,1,4000000,978302124,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3105,1,5000000,978301713,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3114,1,4000000,978302174,1,1,10,48067,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3186,1,4000000,978300019,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3408,1,4000000,978300275,1,1,10,48067,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
y= averagerate.Rating
y.size

53

In [15]:
x

,Gender,Age,Occupation,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
MovieID,,,,,,,,,,,,,,,,,,,,,
1,1,1,10,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
48,1,1,10,0,0,1,1,0,0,0,...,0,0,0,1,0,1,0,0,0,0
150,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
260,1,1,10,1,1,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
527,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
531,1,1,10,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
588,1,1,10,0,0,1,1,1,0,0,...,0,0,0,1,0,0,0,0,0,0
594,1,1,10,0,0,1,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
595,1,1,10,0,0,1,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
608,1,1,10,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
661,1,1,10,0,0,1,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
720,1,1,10,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
745,1,1,10,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
783,1,1,10,0,0,1,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
914,1,1,10,0,0,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
919,1,1,10,0,1,0,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
938,1,1,10,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1022,1,1,10,0,0,1,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1028,1,1,10,0,0,0,1,1,0,0,...,0,0,0,1,0,0,0,0,0,0
1029,1,1,10,0,0,1,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1035,1,1,10,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1097,1,1,10,0,0,0,1,0,0,0,...,1,0,0,0,0,0,1,0,0,0
1193,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1197,1,1,10,1,1,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
1207,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1246,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1270,1,1,10,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
1287,1,1,10,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1545,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1566,1,1,10,0,1,1,1,1,0,0,...,0,0,0,1,0,0,0,0,0,0
1721,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1836,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1907,1,1,10,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1961,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1962,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2018,1,1,10,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2028,1,1,10,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2294,1,1,10,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2321,1,1,10,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2340,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2355,1,1,10,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2398,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2687,1,1,10,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2692,1,1,10,1,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
2762,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2791,1,1,10,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2797,1,1,10,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
2804,1,1,10,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2918,1,1,10,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3105,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3114,1,1,10,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3186,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3408,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
def roundd(x):
    result2=round(x,1)
    return result2

x['Age']=x['Age'].apply(roundd)
x.head()

,Gender,Age,Occupation,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
MovieID,,,,,,,,,,,,,,,,,,,,,
1,1,1,10,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
48,1,1,10,0,0,1,1,0,0,0,...,0,0,0,1,0,1,0,0,0,0
150,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
260,1,1,10,1,1,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
527,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [17]:
x['Occupation']=x['Occupation'].apply(roundd)
x['Gender']=x['Gender'].apply(roundd)
x.head()

,Gender,Age,Occupation,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
MovieID,,,,,,,,,,,,,,,,,,,,,
1,1,1,10,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
48,1,1,10,0,0,1,1,0,0,0,...,0,0,0,1,0,1,0,0,0,0
150,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
260,1,1,10,1,1,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
527,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [18]:
from sklearn.cross_validation import train_test_split
#X_test, X_train, Y_test, Y_train = train_test_split(x, y, test_size=0.01)

D:\anaconda\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [20]:
X_test2,X_train2,Y_test2,Y_train2=train_test_split(x,y, test_size=0.33)
X_test2

,Gender,Age,Occupation,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
MovieID,,,,,,,,,,,,,,,,,,,,,
1566,1,1,10,0,1,1,1,1,0,0,...,0,0,0,1,0,0,0,0,0,0
2762,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1197,1,1,10,1,1,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
608,1,1,10,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
919,1,1,10,0,1,0,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
720,1,1,10,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3105,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1270,1,1,10,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
1097,1,1,10,0,0,0,1,0,0,0,...,1,0,0,0,0,0,1,0,0,0
914,1,1,10,0,0,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
150,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3408,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1022,1,1,10,0,0,1,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1207,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1246,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3114,1,1,10,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
527,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2355,1,1,10,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1962,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
745,1,1,10,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
1287,1,1,10,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2804,1,1,10,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
531,1,1,10,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2340,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
783,1,1,10,0,0,1,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
3186,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
260,1,1,10,1,1,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
2918,1,1,10,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
595,1,1,10,0,0,1,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2294,1,1,10,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1961,1,1,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
661,1,1,10,0,0,1,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
48,1,1,10,0,0,1,1,0,0,0,...,0,0,0,1,0,1,0,0,0,0
588,1,1,10,0,0,1,1,1,0,0,...,0,0,0,1,0,0,0,0,0,0
1,1,1,10,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [21]:
Y_test2

MovieID
1566    4000000
2762    4000000
1197    3000000
608     4000000
919     4000000
720     3000000
3105    5000000
1270    5000000
1097    4000000
914     3000000
150     5000000
3408    4000000
1022    5000000
1207    4000000
1246    4000000
3114    4000000
527     5000000
2355    5000000
1962    4000000
745     3000000
1287    5000000
2804    5000000
531     4000000
2340    3000000
783     4000000
3186    4000000
260     4000000
2918    4000000
595     5000000
2294    4000000
1961    5000000
661     3000000
48      5000000
588     4000000
1       5000000
Name: Rating, dtype: int64

In [24]:
from sklearn import metrics
from sklearn import tree

clf= tree.DecisionTreeRegressor()
clf=clf.fit(X_train2,Y_train2)

predicted= clf.predict(X_test2)
print(clf.score(x,y))
print(metrics.accuracy_score(Y_test2,predicted))

0.0381020692054

ValueError: Classification metrics can't handle a mix of multiclass and continuous targets

In [22]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 1000, random_state = 0)
regressor=regressor.fit(X_train2,Y_train2)

In [23]:
X_train.head()

,Gender,Age,Occupation,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
MovieID,,,,,,,,,,,,,,,,,,,,,
1029,1,1,10,0,0,1,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [24]:
from sklearn.ensemble import RandomForestClassifier
import pydot
forest_clf = RandomForestClassifier()
forest_clf.fit(X_train2, Y_train2)
tree.export_graphviz(forest_clf.estimators_[0], out_file='tree_from_forest.dot')
(graph,) = pydot.graph_from_dot_file('tree_from_forest.dot')
graph.write_png('tree_from_forest.png')

In [25]:
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier,export_graphviz
import graphviz
import io
import pydotplus
from scipy import misc
from matplotlib import pyplot as plt
%matplotlib inline 

features=X_train.columns
def show(tree,features,path):
    f=io.StringIO()
    export_graphviz(tree,out_file=f,feature_names=features)
    pydotplus.graph_from_dot_data(f.getvalue()).write_png(path)
    img=misc.imread(path)
    plt.rcParams["figure.figsize"] = (450,450)
    plt.imshow(img)
                                  
show(regressor,features,"agac.png")

NotFittedError: This RandomForestRegressor instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

In [ ]:
predicted

In [26]:
predicted.size

34

In [27]:
from sklearn.metrics import mean_squared_error
mean_squared_error(Y_test2,predicted)

911764705882.35291

In [ ]:
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier,export_graphviz
import graphviz
import io
import pydotplus
from scipy import misc
from matplotlib import pyplot as plt
%matplotlib inline 

features=X_train.columns
def show(tree,features,path):
    f=io.StringIO()
    export_graphviz(tree,out_file=f,feature_names=features)
    pydotplus.graph_from_dot_data(f.getvalue()).write_png(path)
    img=misc.imread(path)
    plt.rcParams["figure.figsize"] = (450,450)
    plt.imshow(img)
                                  
show(clf,features,"agac.png")